#!/usr/bin/env bash
# Build Reaper.app + DMG and publish to GitHub Releases (DMG only).
#
# GitHub always shows automatic "Source code (zip)" and "Source code (tar.gz)"
# links on every release; those cannot be removed. Release notes warn users to
# download the DMG instead.
#
# Usage:
#   ./scripts/release-macos.sh              # build + create or update release
#   REAPER_SKIP_BUILD=1 ./scripts/release-macos.sh   # upload existing DMG
#   REAPER_RELEASE_NOTES=notes.md ./scripts/release-macos.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' "$ROOT/Cargo.toml" | head -1)"
ARCH="$(uname -m)"
TAG="v${VERSION}"
DMG="$ROOT/dist/Reaper-${VERSION}-macos-${ARCH}.dmg"
TITLE="Reaper ${VERSION} (macOS ${ARCH})"

if [[ -z "$VERSION" ]]; then
  echo "Could not read version from Cargo.toml" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required (https://cli.github.com/)" >&2
  exit 1
fi

if [[ "${REAPER_SKIP_BUILD:-}" == "1" ]]; then
  if [[ ! -f "$DMG" ]]; then
    echo "DMG not found at $DMG (run without REAPER_SKIP_BUILD=1 first)" >&2
    exit 1
  fi
else
  "$ROOT/scripts/build-macos-dmg.sh"
fi

if [[ -n "${REAPER_RELEASE_NOTES:-}" ]]; then
  NOTES_FILE="$REAPER_RELEASE_NOTES"
  if [[ ! -f "$NOTES_FILE" ]]; then
    echo "Release notes file not found: $NOTES_FILE" >&2
    exit 1
  fi
else
  NOTES_FILE="$(mktemp)"
  cat >"$NOTES_FILE" <<EOF
macOS ${ARCH} build.

**Install:** download the **DMG** below. Ignore GitHub's automatic "Source code (zip)" and "Source code (tar.gz)" links — those are generated by GitHub and are not distributable builds.

Drag Reaper.app to Applications, then launch.

**Tip:** opening the .dmg repeatedly mounts a new Finder volume each time — eject old Reaper drives or run scripts/eject-reaper-dmgs.sh.
EOF
fi

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "Uploading DMG to existing release ${TAG}…"
  gh release upload "$TAG" "$DMG" --clobber
  gh release edit "$TAG" --title "$TITLE" --notes-file "$NOTES_FILE"
else
  echo "Creating release ${TAG}…"
  gh release create "$TAG" "$DMG" --title "$TITLE" --notes-file "$NOTES_FILE"
fi

if [[ -z "${REAPER_RELEASE_NOTES:-}" ]]; then
  rm -f "$NOTES_FILE"
fi

echo ""
echo "Published: $(gh release view "$TAG" --json url -q .url)"
echo "  Asset: $(basename "$DMG")"
